### ISSUE TITLE
More Information on all publications table

### ISSUE THREAD

**Issue by JacobsonMT** [JacobsonMT/ndb#19]
Add more information to the summary table for all publications. Ex.:

-year
-title (shortened)
-variant event count

**Comment by mbelmadani** [comment]
The data has been cleaned up and is ready to be reloaded. The current latest revision sits at http://www.chibi.ubc.ca/faculty/pavlidis/wiki/download/attachments/40108772/papers-sql-fixed.ods?version=1&modificationDate=1453416245000&api=v2

Once we are ready to load this in, we will have to:\
-Create controller method in PaperService to return an URL constructed from the DOI (ie. the DOI field 
10.1371/journal.pgen.1003443 should become http://dx.doi.org/10.1371/journal.pgen.1003443)
-Add fields in the papers.xhtml view to include the DOI, the paper title, year, author name (instead of the key),  Case, Count, and Design fields.
-Decide whether or not to include the Uddin paper in the database
-Switch the URLs linked in the application to use the DOI

**Comment by mbelmadani** [comment]
Resolved; database updated with new information, and also publications.xhtml and paper.xhtml?paperId=23  (for example) now have updated information.
